# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpendingTrackerUser',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default='0000000', max_length=70),
        ),
    ]
